### ISSUE TITLE
EUI source

### ISSUE THREAD

**Issue by subchannel13** [motib/erigone#1]
Hi!

Is EUI source code open to public? I'm getting an exception when running guided simulation so I wanted to check if it is easy to fix.

**Comment by motib** [comment]
All projects that I post under my name are open source, so feel free to experiment. However, a very long time has gone by since I worked on Erigone/EUI, so I may not be able to help diagnose a problem. You can try posting a minimal example and its output, but no promises :-(.

**Comment by subchannel13** [comment]
Thank you for fast response!

I can't find any Java code (other than examples/GenerateSatERI.java) in this repository, is EUI published somewhere else?

I'll open separate issue for simulation exception.

**Comment by motib** [comment]
Hi @subchannel13, I feel really stupid ... I forgot to add the EUI source code to the repo. It is now there in the eui directory, along with an ico icon file. The building instructions in the user guide work. Thanks for bringing this to my attention!!

**Comment by subchannel13** [comment]
Great, thanks!

By the way, EUI is the best formal software verification tool I've found so far.
